name: myenv
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel # required for jupyter notebook in VS Code
  - ipywidgets
  - pandas
  - numpy
  - matplotlib
  - plotly
  - seaborn
#   - pip  # if you need more packages installed from pip 
#   - pip:
#     - foo
